server:
  port: 80

spring:
  application:
    name: web-editor
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri:
          username:
          password:
          search-paths: {application}